### ISSUE TITLE
Copyright Infringement

### ISSUE THREAD

**Issue by JeromSar** [CreeperCoders/ProjectX#5]
@buildcarter8 @zD12 @xDestroyer217 
Hello,

It has come to my attention that this repository contains copyrighted material in violation of its provided license.
The material in question is released under the TotalFreedom General License (TFGL) [Version 1.0](https://github.com/TotalFreedom/License/blob/03bfff8a00006d46653661129004b534d6ebedc3/LICENSE.md) or [Version 2.0](https://github.com/TotalFreedom/License/blob/7e1a8d078b1c310b8ed618ce215ab77e2a7a099e/LICENSE.md) depending on the time infringing material was introduced to this repository.

Copyrighted material included in this repository violates its license due to one or more of the following:
* Redistributions of the material do not retain its copyright license in its exact form.
* The original authors of this software have been misrepresented or not reprepresented at all in one or more of the following locations:
  * _plugin.yml_ under `authors`
  * _README.md_
  * _TFM_Util.java_ under `DEVELOPERS`
* Redistributions of the material in question are available in non-source, object, packaged or compiled form.

In order to comply with the infringed material's license and its copyright restrictions, please either:
  a) Remove the copyrighted material from this repository; or
  b) Edit or adjust the required source files as necessary to comply with TFGL.
  
I hope to have properly and sufficiently informed you of the violations in this repository. If you have any further questions, don't hesitate to contact me.

Thanks in advance,
Jerom

**Comment by buildcarter8** [comment]
This makes absolutely no sense this project contains nothing from totalfreedommod if it does please show me and I'll be more then happy to fix it but if it DOSNT don't come at me just because I went rouge

**Comment by buildcarter8** [comment]
And if you do find the file please tell me what I need to do to keep this project going as I have plans for it still

**Comment by buildcarter8** [comment]
will that work @JeromSar

**Comment by JeromSar** [comment]
@buildcarter8
The following files contain material that is licensed under TFGL.

* https://github.com/CreeperCoders/ProjectX/blob/master/src/org/CreeperCoders/ProjectX/Projectx.java
* https://github.com/CreeperCoders/ProjectX/blob/master/src/org/CreeperCoders/ProjectX/Commands/CantFindPlayerException.java
* https://github.com/CreeperCoders/ProjectX/blob/master/src/org/CreeperCoders/ProjectX/Commands/PX_Command.java

In order to comply with the infringed material's license and its copyright restrictions, please either:
a) Remove the copyrighted material from this repository; or
b) Edit or adjust the required source files as necessary to comply with TFGL.

In this scenario, you can continue to use this material by explicitly stating that the material is available under TFGL. You can do so by adding a header to said files containing the following:
```
/*
* Copyright (c) 2011-2015, Steven Lawson
* Copyright (c) 2012-2015, Jerom van der Sar
*  
* Licensed under the TotalFreedom General License (TFGL) Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* https://github.com/TotalFreedom/License/blob/master/LICENSE.md
*/
```

**Comment by buildcarter8** [comment]
Issue has been fixed @JeromSar Thanks for pointing that out

**Comment by JeromSar** [comment]
@buildcarter8 Thanks for the quick fix. All is fine now :)
Note that you may want to move the comments to the start of the files for clarity, but that's not absolutely necessary.

Cheers,
Jerom

**Comment by buildcarter8** [comment]
Locked Issue
